version: "3"
services:
  db:
    image: postgres:13.3
    container_name: malachite_db
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - ./pgdata:/var/lib/postgresql/data
#    ports:
#      - "${HOST_DB_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
  app:
    container_name: malachite
    env_file:
      - .env
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    entrypoint: ["sh", "/app/entrypoint.sh"]
