# Generated by Django 4.1.2 on 2022-10-27 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTnvedCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tnved_id', models.IntegerField(unique=True)),
                ('tnved_code', models.IntegerField()),
                ('tnved_name', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modification_time', models.DateTimeField(auto_now=True)),
                ('child_tnved', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='child_codes', to='customs.customtnvedcode', to_field='tnved_id')),
            ],
        ),
    ]
