# Generated by Django 4.1.2 on 2022-10-27 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0002_customtnvedcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=1)),
                ('period', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=5, max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=5, max_digits=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modification_time', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_data', to='customs.country', to_field='country_id')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_data', to='customs.region', to_field='region_id')),
                ('tnved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_data', to='customs.customtnvedcode', to_field='tnved_id')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_data', to='customs.unit', to_field='unit_id')),
            ],
        ),
    ]
