# Generated by Django 4.1.2 on 2022-10-31 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0002_remove_customtnvedcode_parent_tnved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sanction_is', models.IntegerField(unique=True)),
                ('direction', models.CharField(max_length=1)),
                ('country', models.ForeignKey(db_column='sanction_country_id', on_delete=django.db.models.deletion.RESTRICT, related_name='sanctions', to='customs.country', to_field='country_id')),
                ('tnved', models.ForeignKey(db_column='sanction_tnved_id', on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='customs.customtnvedcode')),
            ],
        ),
    ]
