# Generated by Django 4.1.2 on 2022-10-27 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0003_customdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customtnvedcode',
            old_name='child_tnved',
            new_name='parent_tnved',
        ),
    ]
