# Generated by Django 4.1.2 on 2022-10-31 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0003_sanction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sanction',
            old_name='sanction_is',
            new_name='sanction_id',
        ),
    ]
