# Generated by Django 4.1.2 on 2022-11-01 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0004_rename_sanction_is_sanction_sanction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomendation_id', models.IntegerField(unique=True)),
                ('region', models.ForeignKey(db_column='recommendation_region_id', on_delete=django.db.models.deletion.RESTRICT, related_name='recommendations', to='customs.region', to_field='region_id')),
                ('tnved', models.ForeignKey(db_column='recommendation_tnved_id', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='customs.customtnvedcode', to_field='tnved_id')),
            ],
        ),
    ]
