# Generated by Django 4.1.2 on 2022-11-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0006_rename_recomendation_id_recommendation_recommendation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdata',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='customdata',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='customtnvedcode',
            name='tnved_code',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='customtnvedcode',
            name='tnved_name',
            field=models.CharField(max_length=400),
        ),
    ]
