# Generated by Django 4.1.2 on 2022-11-04 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0007_exporttoexel_alter_customdata_quantity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExportToExel',
        ),
    ]
